app/__init__.py
from flask import Flask
from config import Config
from .site.routes import site
from .authentication.routes import auth
from .api.routes import api

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from models import db as root_db, login_manager, ma
from flask_cors import CORS
from helpers import JSONEncoder


app = Flask(__name__)
CORS(app)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)

app.json_encoder = JSONEncoder
app.config.from_object(Config)
root_db.init_app(app)
login_manager.init_app(app)
ma.init_app(app)
migrate = Migrate(app, root_db)

app/api/routes.py
from flask import Blueprint, request, jsonify, render_template
from helpers import token_required
from models import db, User, Car, car_schema, car_schemas

api = Blueprint('api',__name__, url_prefix='/api')

@api.route('/getdata')
def getdata():
    return {'yee': 'haw'}

@api.route('/newcar', methods = ['POST'])
@token_required
def create_contact(current_user_token):
    make = request.json['make']
    _model = request.json['_model']
    year = request.json['year']
    vin = request.json['vin']
    user_token = current_user_token.token

    print(f'BIG TESTER: {current_user_token.token}')

    car = Car(make, _model, year, vin, user_token = user_token )

    db.session.add(car)
    db.session.commit()

    response = car_schema.dump(car)
    return jsonify(response)

@api.route('/seecars', methods = ['GET'])
@token_required
def see_cars(current_user_token):
    u = current_user_token.token
    data = Car.query.filter_by(user_token = u).all()
    response = car_schemas.dump(data)
    return jsonify(response)

@api.route('/seecar/<id>', methods = ['get'])
@token_required
def get_single_contact(current_user_token, id):
    car = Car.query.get(id)
    response = car_schema.dump(car)
    return jsonify(response)

@api.route('/updatecar/<id>', methods = ['get', 'put'])
@token_required
def update(current_user_token, id):
    car = Car.query.get(id)
    car.make = request.json['make']
    car._model = request.json['_model']
    car.year = request.json['year']
    car.vin = request.json['vin']
    car.user_token = current_user_token.token

    db.session.commit()
    return jsonify(car_schema.dump(car))

@api.route('/delcar/<id>', methods = ['DELETE'])
@token_required
def delete_contact(current_user_token, id):
    car = Car.query.get(id)
    db.session.delete(car)
    db.session.commit()
    response = car_schema.dump(car)
    return jsonify(response)

app/authentication/routes.py
#from curses import use_default_colors
from forms import UserLoginForm, UserSignUpForm
from models import User, db, check_password_hash
from flask import Blueprint, render_template, request, redirect, url_for, flash

from flask_login import login_user, logout_user, LoginManager, current_user, login_required

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserSignUpForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            first_name = form.first_name.data
            last_name = form.last_name.data
            print(email, password, first_name, last_name)

            user = User(email, first_name = str(first_name), last_name = str(last_name), password = password, )

            db.session.add(user)
            db.session.commit()

            flash(f'You have successfully created a user account {email}', 'User-created')
            return redirect(url_for('site.home'))
    except:
        raise Exception('Invalid form data: Please check your form')

    return render_template('sign_up.html', form=form)



@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email,password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successful in your initiation. Congratulations, and welcome to the Jedi Knights', 'auth-success')
                return redirect(url_for('site.profile'))
            else:
                flash('You have failed in your attempt to access this content.', 'auth-failed')
    except:
        raise Exception('Invalid form data: Please check your form')
    return render_template('sign_in.html', form=form)

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('site.home'))

app/site/routes.py
from flask import Blueprint, render_template

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
def profile():
    return render_template('profile.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<!-- This is the outside of the website. (things that will be the same no matter what page you view) we will input content into the jinja -->


<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" href="../static/CSS/main.css">
<title>Inventory</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg py-3 fixed-top">
        <div class="container">
            <a href="#" class="navbar-brand boxitem">Inventory</a>
            <button 
                class="navbar-toggler " 
                type="button" 
                data-bs-toggle="collapse" 
                data-bs-target="#navmenu"

            ><div><span class="navbar-toggler-icon boxitem"></span></button>
            <div class="collapse navbar-collapse" id="navmenu">
                <ul class="navbar-nav ms-auto">
                    <li class="">
                        <a href="{{ url_for('site.home') }}" class="boxitem nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('site.profile') }}" class="boxitem nav-link">Profile</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.logout') }}" class="boxitem nav-link">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signin') }}" class="boxitem nav-link">Sign In</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signup') }}" class="boxitem nav-link">Sign Up</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% block content %}
{% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/outline.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<!-- This is the outside of the website. (things that will be the same no matter what page you view) we will input content into the jinja -->


<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Inventory</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg py-3 fixed-top">
        <div class="container">
            <a href="#" class="navbar-brand boxitem">Inventory</a>
            <button 
                class="navbar-toggler " 
                type="button" 
                data-bs-toggle="collapse" 
                data-bs-target="#navmenu"

            ><div><span class="navbar-toggler-icon boxitem"></span></button>
            <div class="collapse navbar-collapse" id="navmenu">
                <ul class="navbar-nav ms-auto">
                    <li class="">
                        <a href="{{ url_for('site.home') }}" class="boxitem nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('site.profile') }}" class="boxitem nav-link">Profile</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.logout') }}" class="boxitem nav-link">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signin') }}" class="boxitem nav-link">Sign In</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signup') }}" class="boxitem nav-link">Sign Up</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% block content %}
{% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/sign_in_forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = 'form-control', placeholder = 'place email here ') }}
        </fieldset>
    </div>

        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Place password here ") }}
        </fieldset>

        <!-- Submit button area -->
        {{ form.submit_button(class = "btn btn-primary btn-block mt-2")}}

</form>

app/templates/sign_up_form.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = 'form-control', placeholder = 'email') }}
        </fieldset>
        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "password") }}
        </fieldset>
        <fieldset id="first_name-field">
            {{ form.first_name.label }}
            {{ form.first_name(class = "form-control", placeholder = "first_name") }}
        </fieldset>
        <fieldset id="last_name-field">
            {{ form.last_name.label }}
            {{ form.last_name(class = "form-control", placeholder = "last_name") }}
        </fieldset>

        <!-- Submit button area -->
        {{ form.submit_button(class = "btn btn-primary btn-block mt-2")}}
    </div>
</form>